### PR TITLE
[explainer] Use type expansion rather than equality

### PR DESCRIPTION
**Pull request by tlively**
When looking up a type on the context, expand it (using `~~`) into the
expected composite type instead of using equality (`=`). Also fix some
places where equality should have been used when looking up tags.

### CODE REVIEW

**Review by conrad-watt — APPROVED** [review]
lgtm

**Comment by conrad-watt** [comment]
I realise by merging https://github.com/WebAssembly/stack-switching/pull/68 already I may have messed with your plans - sorry! I won't touch this one.

**Review by rossberg — APPROVED** [review]
LGTM.

Btw, if we want to be precise and faithful to the actual spec syntax, then cases like `C.types[$t] ~~ [t1*] -> [t2*]` need to be `C.types[$t] ~~ func [t1*] -> [t2*]`.

**Comment by tlively** [comment]
Thanks, added `func` to the expanded function types now.

**Pull request merged**
