### PR TITLE
Collect previous design documents in `stack-switching/design-notes`.

### PR DESCRIPTION
**Pull request by dhil**
This patch collects the documents of `proposals/bag-o-stacks` and `proposals/continuations` directories into `proposals/stack-switching/design-notes`. The examples in `proposals/continuations/examples` have been copied over to `proposals/stack-switching/examples`.

The `README.md` has been updated as well.

### CODE REVIEW

**Comment by fgmccabe** [comment]
We had previously agreed to keeping these. Putting them in a separate directory is fine; but I would suggest 'design notes' rather than 'legacy'. This applies particularly (IMO) to the Bag of Stacks stuff. As for the typed continuations work, I would suggest removing files that are actually duplicated; and if there is stuff remaining, then put that too into a design notes directory.

**Comment by dhil** [comment]
@fgmccabe done!

**Review by tlively — COMMENTED** [review]
This cleanup makes sense to me 👍

**Comment by dhil** [comment]
I've moved the `proposals/stack-switching-requirements/requirements.md` to `proposals/stack-switching/design-notes/requirements.md`. I think that's it for collecting all the the proposal documents under a single directory. I will merge this PR by the end of the week, unless somebody objects in the meantime.

**Pull request merged**
